import { Menu, Plus, Sparkles, Trash2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import AppCard from "../../components/base/AppCard";
import AppPage from "../../components/base/AppPage";
import AppStatusMessage from "../../components/base/AppStatusMessage";
import AiChatComposer from "./components/AiChatComposer";
import AiChatMessage from "./components/AiChatMessage";
import AiConversationSidebar from "./components/AiConversationSidebar";
import AiResultVisual from "./components/AiResultVisual";
import { deleteConversation, getConversation, getConversations, getStatus, sendMessage } from "./services/aiService";
import type { AiChatResponse, AiConversation, AiMessage } from "./types";
import "./cj-intelligence.css";

const suggestions = ["Analizar gastos del mes", "Comparar este mes con el anterior", "Revisar asistencia", "Analizar órdenes de compra", "Detectar variaciones", "Resumen gerencial"];
const friendlyError = (error: unknown) => { const status = (error as { response?: { status?: number; data?: { errorCode?: string } } })?.response?.status; const code = (error as { response?: { data?: { errorCode?: string } } })?.response?.data?.errorCode; if (status === 401) return "Tu sesión no es válida. Inicia sesión nuevamente."; if (status === 403 || code === "AI_PERMISSION_DENIED") return "No tienes permisos para utilizar CJ Intelligence."; if (code === "MissingScopeDefinition") return "Esta fuente de datos todavía no ha sido habilitada para CJ Intelligence."; if (code === "UnauthorizedDataScope") return "No tienes acceso autorizado a la información necesaria para responder esta consulta."; if (code === "AI_DISABLED") return "CJ Intelligence está deshabilitado en este entorno."; if (code === "OPENAI_UNAVAILABLE") return "El servicio de inteligencia artificial no está disponible temporalmente."; if (code === "SQL_TIMEOUT") return "El análisis excedió el tiempo permitido. Intenta acotar la consulta."; return "No fue posible completar el análisis. Intenta nuevamente."; };

export default function CjIntelligencePage() {
  const [status, setStatus] = useState<"loading" | "disabled" | "ready" | "forbidden" | "error">("loading");
  const [conversations, setConversations] = useState<AiConversation[]>([]); const [activeId, setActiveId] = useState<string | null>(null); const [messages, setMessages] = useState<AiMessage[]>([]); const [lastResult, setLastResult] = useState<AiChatResponse | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [sidebarOpen, setSidebarOpen] = useState(false); const abortRef = useRef<AbortController | null>(null); const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const controller = new AbortController(); void getStatus(controller.signal).then((result) => { if (!result.enabled) { setStatus("disabled"); return; } if (!result.available) { setStatus("forbidden"); return; } setStatus("ready"); return getConversations(controller.signal).then(setConversations); }).catch((e) => { if (!controller.signal.aborted) setStatus((e as { response?: { status?: number } })?.response?.status === 403 ? "forbidden" : "error"); }); return () => controller.abort(); }, []);
  useEffect(() => { if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight; }, [messages, loading]);
  const newConversation = () => { setActiveId(null); setMessages([]); setLastResult(null); setError(null); setSidebarOpen(false); };
  const openConversation = async (id: string) => { setError(null); try { const detail = await getConversation(id); setActiveId(id); setMessages(detail.messages.filter((item) => item.role === "user" || item.role === "assistant")); setLastResult(null); setSidebarOpen(false); } catch (e) { setError(friendlyError(e)); } };
  const removeConversation = async (conversation: AiConversation) => { if (!window.confirm(`¿Eliminar "${conversation.titulo || "esta conversación"}"?`)) return; try { await deleteConversation(conversation.idConversacion); setConversations((items) => items.filter((item) => item.idConversacion !== conversation.idConversacion)); if (activeId === conversation.idConversacion) newConversation(); } catch (e) { setError(friendlyError(e)); } };
  const submit = async (message: string) => { if (loading) return; const controller = new AbortController(); abortRef.current = controller; setLoading(true); setError(null); setLastResult(null); setMessages((items) => [...items, { role: "user", content: message }]); try { const result = await sendMessage({ message, conversationId: activeId || undefined }, controller.signal); setMessages((items) => [...items, { role: "assistant", content: result.answer }]); setLastResult(result); const list = await getConversations(); setConversations(list); if (!activeId && list[0]) setActiveId(list[0].idConversacion); } catch (e) { if (!controller.signal.aborted) { setMessages((items) => items.slice(0, -1)); setError(friendlyError(e)); } } finally { abortRef.current = null; setLoading(false); } };
  if (status === "loading") return <AppPage title="CJ Intelligence"><AppStatusMessage tone="info">Verificando disponibilidad de CJ Intelligence...</AppStatusMessage></AppPage>;
  if (status === "disabled") return <AppPage title="CJ Intelligence"><EmptyState title="CJ Intelligence está deshabilitado" text="La función permanece apagada por configuración segura del entorno." /></AppPage>;
  if (status === "forbidden") return <AppPage title="CJ Intelligence"><EmptyState title="No tienes permisos para utilizar CJ Intelligence" text="Solicita el permiso funcional correspondiente al administrador del ERP." /></AppPage>;
  if (status === "error") return <AppPage title="CJ Intelligence"><AppStatusMessage tone="error">No fue posible verificar el estado del módulo. Intenta nuevamente.</AppStatusMessage></AppPage>;
  return <AppPage title="CJ Intelligence" fillHeight><div className="ai-page-shell"><AiConversationSidebar conversations={conversations} activeId={activeId} open={sidebarOpen} onClose={() => setSidebarOpen(false)} onNew={newConversation} onSelect={openConversation} onDelete={removeConversation} /><main className="ai-chat-panel"><div className="ai-mobile-toolbar"><button className="ai-icon-button" onClick={() => setSidebarOpen(true)} aria-label="Abrir conversaciones"><Menu size={19} /></button><span>Conversaciones</span></div><header className="ai-hero"><div><span className="ai-eyebrow">Análisis gerencial seguro</span><h1><Sparkles size={25} /> ¿Qué quieres analizar?</h1><p>Explora información autorizada de tu ERP con respuestas claras y accionables.</p></div><button className="ai-outline-button" onClick={newConversation}><Plus size={16} /> Nueva</button></header><div className="ai-chat-scroll" ref={scrollRef}>{messages.length === 0 ? <Welcome onSuggestion={submit} /> : messages.map((message, index) => <AiChatMessage key={`${message.role}-${index}`} message={message} />)}{loading ? <div className="ai-analyzing"><span className="ai-pulse" /> CJ Intelligence está analizando...</div> : null}{error ? <AppStatusMessage tone="error" style={{ margin: "12px 0" }}>{error}</AppStatusMessage> : null}{lastResult ? <AppCard style={{ marginTop: 14 }}><AiResultVisual result={lastResult} />{lastResult.warnings.map((warning) => <AppStatusMessage key={warning} tone="info" style={{ marginTop: 10 }}>{warning}</AppStatusMessage>)}{lastResult.data.length === 0 ? <AppStatusMessage tone="info">No encontré registros para los criterios solicitados.</AppStatusMessage> : null}</AppCard> : null}</div><AiChatComposer loading={loading} onSend={submit} onCancel={() => abortRef.current?.abort()} /></main></div></AppPage>;
}

function Welcome({ onSuggestion }: { onSuggestion: (value: string) => void }) { return <div className="ai-welcome"><div className="ai-welcome-mark"><Sparkles size={28} /></div><h2>Tu copiloto analítico del ERP</h2><p>Comienza con una pregunta o elige una sugerencia para explorar.</p><div className="ai-suggestion-grid">{suggestions.map((suggestion) => <button key={suggestion} onClick={() => onSuggestion(suggestion)}>{suggestion}</button>)}</div></div>; }
function EmptyState({ title, text }: { title: string; text: string }) { return <AppCard><div className="ai-empty-state"><Sparkles size={32} /><h2>{title}</h2><p>{text}</p></div></AppCard>; }
