CREATE OR ALTER PROCEDURE dbo.sp_Comunicacion_ListarPorEmpleado @IdEmpleadoCj int,@Tipo int=NULL,@SoloNoLeidos bit=NULL,@Pagina int=1,@TamanoPagina int=20 AS BEGIN SET NOCOUNT ON;SET @Pagina=IIF(@Pagina<1,1,@Pagina);SET @TamanoPagina=IIF(@TamanoPagina BETWEEN 1 AND 100,@TamanoPagina,20);SELECT c.IdComunicacion,c.Tipo,c.Titulo,LEFT(c.Mensaje,500) Resumen,c.Prioridad,c.TipoPersistencia,c.FechaCreacion,d.Leido,d.Confirmado,c.PermiteConfirmacion,d.FechaLectura,d.FechaConfirmacion FROM dbo.Comunicacion c JOIN dbo.ComunicacionDestinatario d ON d.IdComunicacion=c.IdComunicacion WHERE d.IdEmpleadoCj=@IdEmpleadoCj AND d.Estado=1 AND c.Activo=1 AND c.Estado=1 AND (@Tipo IS NULL OR c.Tipo=@Tipo) AND (@SoloNoLeidos IS NULL OR (@SoloNoLeidos=1 AND d.Leido=0)) ORDER BY c.FechaCreacion DESC OFFSET (@Pagina-1)*@TamanoPagina ROWS FETCH NEXT @TamanoPagina ROWS ONLY;SELECT COUNT(*) FROM dbo.Comunicacion c JOIN dbo.ComunicacionDestinatario d ON d.IdComunicacion=c.IdComunicacion WHERE d.IdEmpleadoCj=@IdEmpleadoCj AND d.Estado=1 AND c.Activo=1 AND c.Estado=1 AND (@Tipo IS NULL OR c.Tipo=@Tipo) AND (@SoloNoLeidos IS NULL OR (@SoloNoLeidos=1 AND d.Leido=0));END
GO
CREATE OR ALTER PROCEDURE dbo.sp_Comunicacion_Obtener @IdComunicacion bigint,@IdEmpleadoCj int AS BEGIN SELECT c.IdComunicacion,c.Tipo,c.Titulo,c.Mensaje,c.Prioridad,c.TipoPersistencia,c.FechaCreacion,d.Leido,d.Confirmado,c.PermiteConfirmacion,d.FechaLectura,d.FechaConfirmacion,c.IdUsuarioCreacion Remitente FROM dbo.Comunicacion c JOIN dbo.ComunicacionDestinatario d ON d.IdComunicacion=c.IdComunicacion WHERE c.IdComunicacion=@IdComunicacion AND d.IdEmpleadoCj=@IdEmpleadoCj AND d.Estado=1 AND c.Activo=1;END
GO
CREATE OR ALTER PROCEDURE dbo.sp_Comunicacion_MarcarLeido @IdComunicacion bigint,@IdEmpleadoCj int,@IdDispositivo bigint=NULL AS BEGIN UPDATE dbo.ComunicacionDestinatario SET Leido=1,FechaLectura=ISNULL(FechaLectura,SYSUTCDATETIME()) WHERE IdComunicacion=@IdComunicacion AND IdEmpleadoCj=@IdEmpleadoCj AND Estado=1;SELECT IIF(@@ROWCOUNT>0,1,0) Resultado,N'Lectura procesada.' Mensaje;END
GO
CREATE OR ALTER PROCEDURE dbo.sp_Comunicacion_Confirmar @IdComunicacion bigint,@IdEmpleadoCj int,@IdDispositivo bigint=NULL AS BEGIN UPDATE d SET Leido=1,Confirmado=1,FechaLectura=ISNULL(FechaLectura,SYSUTCDATETIME()),FechaConfirmacion=ISNULL(FechaConfirmacion,SYSUTCDATETIME()) FROM dbo.ComunicacionDestinatario d JOIN dbo.Comunicacion c ON c.IdComunicacion=d.IdComunicacion WHERE d.IdComunicacion=@IdComunicacion AND d.IdEmpleadoCj=@IdEmpleadoCj AND d.Estado=1 AND c.PermiteConfirmacion=1;SELECT IIF(@@ROWCOUNT>0,1,0) Resultado,N'Confirmación procesada.' Mensaje;END
GO
CREATE OR ALTER PROCEDURE dbo.sp_Comunicacion_PendientesObligatorias @IdEmpleadoCj int AS BEGIN SELECT c.IdComunicacion,c.Tipo,c.Titulo,c.Mensaje,c.Prioridad,c.TipoPersistencia,c.FechaCreacion,d.Leido,d.Confirmado,c.PermiteConfirmacion FROM dbo.Comunicacion c JOIN dbo.ComunicacionDestinatario d ON d.IdComunicacion=c.IdComunicacion WHERE d.IdEmpleadoCj=@IdEmpleadoCj AND c.Activo=1 AND c.Estado=1 AND c.TipoPersistencia=3 AND d.Confirmado=0;END
GO
CREATE OR ALTER PROCEDURE dbo.sp_DispositivoMovil_Registrar @IdEmpleadoCj int,@IdUsuario nvarchar(100),@PushToken nvarchar(1000),@DeviceId nvarchar(250),@Plataforma varchar(20),@Modelo nvarchar(250)=NULL,@VersionSistema nvarchar(100)=NULL,@VersionApp nvarchar(50)=NULL AS BEGIN UPDATE dbo.DispositivoMovil SET PushToken=@PushToken,Plataforma=@Plataforma,Modelo=@Modelo,VersionSistema=@VersionSistema,VersionApp=@VersionApp,FechaUltimoAcceso=SYSUTCDATETIME(),Activo=1 WHERE IdEmpleadoCj=@IdEmpleadoCj AND DeviceId=@DeviceId;IF @@ROWCOUNT=0 INSERT dbo.DispositivoMovil(IdEmpleadoCj,IdUsuario,PushToken,Plataforma,DeviceId,Modelo,VersionSistema,VersionApp) VALUES(@IdEmpleadoCj,@IdUsuario,@PushToken,@Plataforma,@DeviceId,@Modelo,@VersionSistema,@VersionApp);SELECT 1 Resultado,N'Dispositivo registrado.' Mensaje;END
GO
CREATE OR ALTER PROCEDURE dbo.sp_DispositivoMovil_Desactivar @IdEmpleadoCj int,@IdUsuario nvarchar(100),@DeviceId nvarchar(250) AS BEGIN UPDATE dbo.DispositivoMovil SET Activo=0,FechaUltimoAcceso=SYSUTCDATETIME() WHERE IdEmpleadoCj=@IdEmpleadoCj AND IdUsuario=@IdUsuario AND DeviceId=@DeviceId AND Activo=1;SELECT IIF(@@ROWCOUNT>0,1,0) Resultado,N'Dispositivo procesado.' Mensaje;END
