using System.Data;
using System.Text.Json;
using CjERP.Application.DTOs.Mobile;
using CjERP.Application.Interfaces.Services;
using CjERP.Infrastructure.Persistence.Sql;
using Dapper;
namespace CjERP.Infrastructure.Services;
public sealed class MobileCommunicationService(ISqlCommandFactory sql) : IMobileCommunicationService
{
 public async Task<MobilePagedResultDto<MobileCommunicationDto>> ListarAsync(int idEmpleado, MobileCommunicationListRequestDto request, CancellationToken cancellationToken = default) { var page=Math.Max(1,request.Pagina);var size=Math.Clamp(request.TamanoPagina,1,100);await using var con=sql.CreateConnection();using var grid=await con.QueryMultipleAsync(sql.Create("dbo.sp_Comunicacion_ListarPorEmpleado",new { IdEmpleadoCj=idEmpleado,request.Tipo,request.SoloNoLeidos,Pagina=page,TamanoPagina=size},CommandType.StoredProcedure,cancellationToken));return new(){Items=(await grid.ReadAsync<MobileCommunicationDto>()).AsList(),Pagina=page,TamanoPagina=size,Total=await grid.ReadFirstOrDefaultAsync<int>()}; }
 public async Task<MobileCommunicationDto?> ObtenerAsync(long id,int emp,CancellationToken ct=default){await using var con=sql.CreateConnection();return await con.QueryFirstOrDefaultAsync<MobileCommunicationDto>(sql.Create("dbo.sp_Comunicacion_Obtener",new{IdComunicacion=id,IdEmpleadoCj=emp},CommandType.StoredProcedure,ct));}
 public Task<MobileCommandResultDto> MarcarLeidoAsync(long id,int emp,long? device,CancellationToken ct=default)=>CommandAsync("dbo.sp_Comunicacion_MarcarLeido",id,emp,device,ct);
 public Task<MobileCommandResultDto> ConfirmarAsync(long id,int emp,long? device,CancellationToken ct=default)=>CommandAsync("dbo.sp_Comunicacion_Confirmar",id,emp,device,ct);
 public async Task<IReadOnlyList<MobileCommunicationDto>> PendientesObligatoriasAsync(int emp,CancellationToken ct=default){await using var con=sql.CreateConnection();return (await con.QueryAsync<MobileCommunicationDto>(sql.Create("dbo.sp_Comunicacion_PendientesObligatorias",new{IdEmpleadoCj=emp},CommandType.StoredProcedure,ct))).AsList();}
 public async Task<MobileNotificationSummaryDto> ResumenAsync(int emp,CancellationToken ct=default){await using var con=sql.CreateConnection();return await con.QueryFirstOrDefaultAsync<MobileNotificationSummaryDto>(sql.Create("dbo.sp_Comunicacion_ResumenPorEmpleado",new{IdEmpleadoCj=emp},CommandType.StoredProcedure,ct))??new();}
 public async Task<IReadOnlyList<MobileCommunicationAttachmentDto>> ListarAdjuntosAsync(long id,int emp,CancellationToken ct=default){await using var con=sql.CreateConnection();return (await con.QueryAsync<MobileCommunicationAttachmentDto>(sql.Create("dbo.sp_ComunicacionAdjunto_ListarPorEmpleado",new{IdComunicacion=id,IdEmpleadoCj=emp},CommandType.StoredProcedure,ct))).AsList();}
 public async Task<MobileCommunicationAttachmentDto?> ObtenerAdjuntoAsync(long id,long attachmentId,int emp,CancellationToken ct=default){await using var con=sql.CreateConnection();return await con.QueryFirstOrDefaultAsync<MobileCommunicationAttachmentDto>(sql.Create("dbo.sp_ComunicacionAdjunto_ObtenerPorEmpleado",new{IdComunicacion=id,IdAdjunto=attachmentId,IdEmpleadoCj=emp},CommandType.StoredProcedure,ct));}
 public async Task<MobileCommunicationMonitorDto> MonitorAsync(CancellationToken ct=default){await using var con=sql.CreateConnection();return await con.QueryFirstOrDefaultAsync<MobileCommunicationMonitorDto>(sql.Create("dbo.sp_Comunicacion_Monitor",commandType:CommandType.StoredProcedure,cancellationToken:ct))??new();}
 public async Task<IReadOnlyList<MobileCommunicationDeliveryDetailDto>> ObtenerSeguimientoAsync(long id, CancellationToken ct=default){await using var con=sql.CreateConnection();return (await con.QueryAsync<MobileCommunicationDeliveryDetailDto>(sql.Create("dbo.sp_Comunicacion_Seguimiento",new{IdComunicacion=id},CommandType.StoredProcedure,ct))).AsList();}
 public async Task<MobileCommunicationCreateResultDto> CrearAsync(MobileCommunicationCreateRequestDto request,string usuario,int? empleado,CancellationToken ct=default){await using var con=sql.CreateConnection();return await con.QueryFirstAsync<MobileCommunicationCreateResultDto>(sql.Create("dbo.sp_Comunicacion_Crear",new{request.Tipo,request.Titulo,request.Mensaje,request.Prioridad,request.TipoPersistencia,request.FechaProgramada,request.FechaVencimiento,request.RutaDestino,request.IdReferencia,request.TipoReferencia,request.PermiteConfirmacion,IdUsuarioCreacion=usuario,IdEmpleadoCreacion=empleado,DestinatariosJson=JsonSerializer.Serialize(request.Destinatarios.Distinct())},CommandType.StoredProcedure,ct));}
 public async Task<long> CrearAdjuntoAsync(long id,string nombre,string tipo,long tamano,string ruta,CancellationToken ct=default){await using var con=sql.CreateConnection();return await con.QueryFirstAsync<long>(sql.Create("dbo.sp_ComunicacionAdjunto_Crear",new{IdComunicacion=id,NombreArchivo=nombre,TipoContenido=tipo,TamanoBytes=tamano,RutaAlmacenamiento=ruta},CommandType.StoredProcedure,ct));}
 public async Task<IReadOnlyList<MobileCommunicationRecipientDto>> BuscarDestinatariosAsync(string busqueda,int maximo,CancellationToken ct=default){await using var con=sql.CreateConnection();const string query="SELECT TOP (@Maximo) IdEmpleado AS IdEmpleadoCj, NombreEmpleado, IdCargo, Correo FROM dbo.EmpleadoCj WHERE ISNULL(IdActivo,1)=1 AND (@Busqueda='' OR NombreEmpleado LIKE '%' + @Busqueda + '%' OR CONVERT(varchar(20),IdEmpleado)=@Busqueda) ORDER BY NombreEmpleado";return (await con.QueryAsync<MobileCommunicationRecipientDto>(sql.Create(query,new{Busqueda=(busqueda??string.Empty).Trim(),Maximo=Math.Clamp(maximo,1,100)},CommandType.Text,ct))).AsList();}
 private async Task<MobileCommandResultDto> CommandAsync(string sp,long id,int emp,long? device,CancellationToken ct){await using var con=sql.CreateConnection();return await con.QueryFirstOrDefaultAsync<MobileCommandResultDto>(sql.Create(sp,new{IdComunicacion=id,IdEmpleadoCj=emp,IdDispositivo=device},CommandType.StoredProcedure,ct))??new(){Resultado=0,Mensaje="La operación no devolvió resultado."};}
}
