export type LogisticaSuministroDto = {
  idSuministro?: number | null;
  idSuministroProvisional?: number | null;
  idCliente?: number | null;
  nombreCliente?: string | null;
  idProyecto?: number | null;
  nombreProyecto?: string | null;
  idSite?: string | null;
  nombreSite?: string | null;
  correlativo?: number | null;
  tipoTrabajo?: string | null;
  ot?: string | null;
  idTarea?: number | null;
  tarea?: string | null;
  fechaInicio?: string | null;
  idAprobador?: number | null;
  aprobador?: string | null;
  comentario?: string | null;
  monto?: number | null;
  idMoneda?: number | null;
  moneda?: string | null;
  idEnergia?: number | null;
  tarifa?: string | null;
  idEmpresa?: number | null;
  empresa?: string | null;
  idEstado?: number | null;
  montoClaro?: number | null;
  montoCj?: number | null;
  fechaOnAir?: string | null;
  observacion?: string | null;
  fechaCnx?: string | null;
  nroSuministro?: string | null;
  estadoSuministro?: string | null;
  validacionCliente?: number | null;
  validacion?: string | null;
  fechaEnvioEmail?: string | null;
  fechaDesembolsoClaro?: string | null;
  ceco?: string | null;
  cege?: string | null;
  imagenUrl?: string | null;
  imagenPath?: string | null;
  esActivo?: boolean | null;
  usuarioCreacion?: string | null;
  fechaCreacion?: string | null;
  usuarioActualizacion?: string | null;
  fechaActualizacion?: string | null;
  usuarioEliminacion?: string | null;
  fechaEliminacion?: string | null;
};

export type LogisticaSuministroBuscarRequest = {
  idProvisional?: number | null;
  idCliente?: number | null;
  idProyecto?: number | null;
  fechaInicio?: string | null;
  fechaFin?: string | null;
};

export type LogisticaSuministroKpis = {
  totalPagadoMes?: number | null;
  totalReembolsadoMes?: number | null;
  saldoPendienteReembolso?: number | null;
  suministrosProvisionalesActivos?: number | null;
  casosRiesgoMedio?: number | null;
  casosRiesgoCritico?: number | null;
  porcentajePagosValidacionPrevia?: number | null;
  indiceRecupero?: number | null;
};

export type LogisticaSuministroInsertRequest = {
  idCliente: number;
  idProyecto: number;
  idSite: string;
  correlativo?: number | null;
  tipoTrabajo?: string | null;
  ot?: string | null;
  idTarea?: number | null;
  fechaInicio?: string | null;
  idAprobador?: number | null;
  comentario?: string | null;
  monto?: number | null;
  idMoneda?: number | null;
  idEnergia?: number | null;
  idEmpresa?: number | null;
  idEstado?: number | null;
  montoClaro?: number | null;
  montoCj?: number | null;
  fechaOnAir?: string | null;
  observacion?: string | null;
  fechaCnx?: string | null;
  nroSuministro?: string | null;
  fechaEnvioEmail?: string | null;
  fechaDesembolsoClaro?: string | null;
  validacionCliente?: number | null;
  ceco?: string | null;
  cege?: string | null;
  imagenUrl?: string | null;
  imagenPath?: string | null;
};

export type LogisticaSuministroUpdateRequest = {
  idProvisional?: number | null;
  idCliente: number;
  idProyecto: number;
  idSite: string;
  correlativo?: number | null;
  tipoTrabajo?: string | null;
  ot?: string | null;
  idTarea?: number | null;
  fechaInicio?: string | null;
  idAprobador?: number | null;
  comentario?: string | null;
  monto?: number | null;
  idMoneda?: number | null;
  idEnergia?: number | null;
  idEmpresa?: number | null;
  idEstado?: number | null;
  montoClaro?: number | null;
  montoCj?: number | null;
  fechaOnAir?: string | null;
  observacion?: string | null;
  fechaCnx?: string | null;
  nroSuministro?: string | null;
  fechaEnvioEmail?: string | null;
  fechaDesembolsoClaro?: string | null;
  validacionCliente?: number | null;
  ceco?: string | null;
  cege?: string | null;
  imagenUrl?: string | null;
  imagenPath?: string | null;
};
