export type LogisticaRecojoDto = {
  idRecojo: number;
  idCliente: number;
  nombreCliente: string;
  idProyecto: number;
  nombreProyecto: string;
  idSite: string;
  correlativo: number;
  nombreSite: string;
  solicitud: string;
  clave: string;
  idEmpresa?: number | null;
  agencia: string;
  nroGuia: string;
  idUbigeo?: number | null;
  nombreUbigeo: string;
  detalleUbigeo: string;
  fechaSalida?: string | null;
  fechaLlegada?: string | null;
  observacion: string;
  idResponsable?: number | null;
  responsable: string;
  fechaRecojo?: string | null;
  rutaImagenGuia: string;
  idResponsableRecojo?: number | null;
  responsableOtro: string;
  usuarioCreacion: string;
  fechaCreacion?: string | null;
  usuarioActualizacion: string;
  fechaActualizacion?: string | null;
  usuarioEliminacion: string;
  fechaEliminacion?: string | null;
  esActivo: boolean;
};

export type LogisticaRecojoBuscarRequest = {
  idRecojo?: number | null;
  idCliente?: number | null;
  idProyecto?: number | null;
  idSite?: string | null;
  correlativo?: number | null;
  solicitud?: string | null;
  clave?: string | null;
  idEmpresa?: number | null;
  nroGuia?: string | null;
  idUbigeo?: number | null;
  idResponsable?: number | null;
  idResponsableRecojo?: number | null;
  esActivo?: boolean | null;
};

export type LogisticaRecojoInsertRequest = {
  idCliente: number;
  idProyecto: number;
  idSite: string;
  correlativo: number;
  solicitud: string;
  clave: string;
  idEmpresa?: number | null;
  nroGuia: string;
  idUbigeo?: number | null;
  detalleUbigeo: string;
  fechaSalida?: string | null;
  fechaLlegada?: string | null;
  observacion: string;
  idResponsable?: number | null;
  fechaRecojo?: string | null;
  rutaImagenGuia: string;
  idResponsableRecojo?: number | null;
  usuarioCreacion: string;
};
